//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDescription
    {
        public System.Guid Id { get; set; }
        public string EmployeeId { get; set; }
        public string JobPurposes { get; set; }
        public string KeyAccountabilities { get; set; }
        public Nullable<bool> IsReportToConfirmed { get; set; }
        public Nullable<bool> IsHOBUConfirmed { get; set; }
        public Nullable<System.DateTime> ReportToConfirmedDate { get; set; }
        public Nullable<System.DateTime> HOBUConfirmedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
