//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectiveSub
    {
        public string Id { get; set; }
        public System.Guid ObjectiveMainId { get; set; }
        public string KPI { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> SelfAppraisal { get; set; }
        public string Comments { get; set; }
        public string EvidenceFile { get; set; }
        public Nullable<bool> IsObjectiveApproved { get; set; }
        public Nullable<decimal> PerfomenseAppraisal { get; set; }
        public Nullable<System.DateTime> PerfomenseAppraisalDate { get; set; }
        public string PerfomenseAppraisalBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Target { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Title { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ObjectiveMain ObjectiveMain { get; set; }
    }
}
